#!/usr/bin/env bash

set -e

if [[ -z $(which rdmsr) ]]; then
	echo "msr-tools required!" >&2
	exit 1
fi

if [[ ! -z $1 && $1 != "disable" && $1 != "enable" ]]; then
	echo "Invalid argument: $1" >&2
	echo "Usage: $(basename $0) [disable|enable]"
	exit 1
fi

cores=$(cat /proc/cpuinfo | grep processor | awk '{print $3}')

if [[ $1 == "disable" ]]; then
	for core in $cores; do
		wrmsr -p${core} 0x1a0 0x4000850089
	done
elif [[ $1 == "enable" ]]; then
	for core in $cores; do
		wrmsr -p${core} 0x1a0 0x850089
	done
fi

for core in $cores; do
	state=$(rdmsr -p${core} 0x1a0 -f 38:38)
        if [[ $state -eq 1 ]]; then
		echo "core ${core}: disabled"
	else
		echo "core ${core}: enabled"
	fi
done
